/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2021-05-27 13:09:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AddNewBooking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1622119859642L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1622120058930L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\r\n");
      out.write("=========================================================\r\n");
      out.write("* Argon Dashboard - v1.2.0\r\n");
      out.write("=========================================================\r\n");
      out.write("* Product Page: https://www.creative-tim.com/product/argon-dashboard\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("* Copyright  Creative Tim (http://www.creative-tim.com)\r\n");
      out.write("* Coded by www.creative-tim.com\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("=========================================================\r\n");
      out.write("* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <!-- Sidenav -->\r\n");
      out.write("  <nav class=\"sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white\" id=\"sidenav-main\">\r\n");
      out.write("    <div class=\"scrollbar-inner\">\r\n");
      out.write("      <!-- Brand -->\r\n");
      out.write("      <div class=\"sidenav-header  align-items-center\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"javascript:void(0)\">\r\n");
      out.write("          <img src=\"assets/img/brand/blue.png\" class=\"navbar-brand-img\" alt=\"...\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"navbar-inner\">\r\n");
      out.write("        <!-- Collapse -->\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"sidenav-collapse-main\">\r\n");
      out.write("          <!-- Nav items -->\r\n");
      out.write("          <ul class=\"navbar-nav\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"dashboard.jsp\">\r\n");
      out.write("                <i class=\"ni ni-tv-2 text-primary\"></i>\r\n");
      out.write("                <span class=\"nav-link-text\">Dashboard</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link active\" href=\"AddNewBooking.jsp\">\r\n");
      out.write("                <i class=\"ni ni-planet text-orange\"></i>\r\n");
      out.write("                <span class=\"nav-link-text\">Add New Booking</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"map.html\">\r\n");
      out.write("                <i class=\"ni ni-pin-3 text-primary\"></i>\r\n");
      out.write("                <span class=\"nav-link-text\">Google</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"profile.html\">\r\n");
      out.write("                <i class=\"ni ni-single-02 text-yellow\"></i>\r\n");
      out.write("                <span class=\"nav-link-text\">Profile</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"tables.html\">\r\n");
      out.write("                <i class=\"ni ni-bullet-list-67 text-default\"></i>\r\n");
      out.write("                <span class=\"nav-link-text\">Tables</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"login.html\">\r\n");
      out.write("                <i class=\"ni ni-key-25 text-info\"></i>\r\n");
      out.write("                <span class=\"nav-link-text\">Login</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"register.html\">\r\n");
      out.write("                <i class=\"ni ni-circle-08 text-pink\"></i>\r\n");
      out.write("                <span class=\"nav-link-text\">Register</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"upgrade.html\">\r\n");
      out.write("                <i class=\"ni ni-send text-dark\"></i>\r\n");
      out.write("                <span class=\"nav-link-text\">Upgrade</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <!-- Divider -->\r\n");
      out.write("          <hr class=\"my-3\">\r\n");
      out.write("          <!-- Heading -->\r\n");
      out.write("          <h6 class=\"navbar-heading p-0 text-muted\">\r\n");
      out.write("            <span class=\"docs-normal\">Documentation</span>\r\n");
      out.write("          </h6>\r\n");
      out.write("          <!-- Navigation -->\r\n");
      out.write("          <ul class=\"navbar-nav mb-md-3\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"https://demos.creative-tim.com/argon-dashboard/docs/getting-started/overview.html\" target=\"_blank\">\r\n");
      out.write("                <i class=\"ni ni-spaceship\"></i>\r\n");
      out.write("                <span class=\"nav-link-text\">Getting started</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"https://demos.creative-tim.com/argon-dashboard/docs/foundation/colors.html\" target=\"_blank\">\r\n");
      out.write("                <i class=\"ni ni-palette\"></i>\r\n");
      out.write("                <span class=\"nav-link-text\">Foundation</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"https://demos.creative-tim.com/argon-dashboard/docs/components/alerts.html\" target=\"_blank\">\r\n");
      out.write("                <i class=\"ni ni-ui-04\"></i>\r\n");
      out.write("                <span class=\"nav-link-text\">Components</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"https://demos.creative-tim.com/argon-dashboard/docs/plugins/charts.html\" target=\"_blank\">\r\n");
      out.write("                <i class=\"ni ni-chart-pie-35\"></i>\r\n");
      out.write("                <span class=\"nav-link-text\">Plugins</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link active active-pro\" href=\"upgrade.html\">\r\n");
      out.write("                <i class=\"ni ni-send text-dark\"></i>\r\n");
      out.write("                <span class=\"nav-link-text\">Upgrade to PRO</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- Main content -->\r\n");
      out.write("  <div class=\"main-content\" id=\"panel\">\r\n");
      out.write("    <!-- Topnav -->\r\n");
      out.write("   \r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"Start your development with a Dashboard for Bootstrap 4.\">\r\n");
      out.write("  <meta name=\"author\" content=\"Creative Tim\">\r\n");
      out.write("  <title>Argon Dashboard - Free Dashboard for Bootstrap 4</title>\r\n");
      out.write("  <!-- Favicon -->\r\n");
      out.write("  <link rel=\"icon\" href=\"assets/img/brand/favicon.png\" type=\"image/png\">\r\n");
      out.write("  <!-- Fonts -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700\">\r\n");
      out.write("  <!-- Icons -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assets/vendor/nucleo/css/nucleo.css\" type=\"text/css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assets/vendor/@fortawesome/fontawesome-free/css/all.min.css\" type=\"text/css\">\r\n");
      out.write("  <!-- Page plugins -->\r\n");
      out.write("  <!-- Argon CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assets/css/argon.css?v=1.2.0\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <nav class=\"navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("          <!-- Search form -->\r\n");
      out.write("          <form class=\"navbar-search navbar-search-light form-inline mr-sm-3\" id=\"navbar-search-main\">\r\n");
      out.write("            <div class=\"form-group mb-0\">\r\n");
      out.write("              <div class=\"input-group input-group-alternative input-group-merge\">\r\n");
      out.write("                <div class=\"input-group-prepend\">\r\n");
      out.write("                  <span class=\"input-group-text\"><i class=\"fas fa-search\"></i></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input class=\"form-control\" placeholder=\"Search\" type=\"text\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"button\" class=\"close\" data-action=\"search-close\" data-target=\"#navbar-search-main\" aria-label=\"Close\">\r\n");
      out.write("              <span aria-hidden=\"true\">×</span>\r\n");
      out.write("            </button>\r\n");
      out.write("          </form>\r\n");
      out.write("          <!-- Navbar links -->\r\n");
      out.write("          <ul class=\"navbar-nav align-items-center  ml-md-auto \">\r\n");
      out.write("            <li class=\"nav-item d-xl-none\">\r\n");
      out.write("              <!-- Sidenav toggler -->\r\n");
      out.write("              <div class=\"pr-3 sidenav-toggler sidenav-toggler-dark\" data-action=\"sidenav-pin\" data-target=\"#sidenav-main\">\r\n");
      out.write("                <div class=\"sidenav-toggler-inner\">\r\n");
      out.write("                  <i class=\"sidenav-toggler-line\"></i>\r\n");
      out.write("                  <i class=\"sidenav-toggler-line\"></i>\r\n");
      out.write("                  <i class=\"sidenav-toggler-line\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item d-sm-none\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"#\" data-action=\"search-show\" data-target=\"#navbar-search-main\">\r\n");
      out.write("                <i class=\"ni ni-zoom-split-in\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item dropdown\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"#\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                <i class=\"ni ni-bell-55\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"dropdown-menu dropdown-menu-xl  dropdown-menu-right  py-0 overflow-hidden\">\r\n");
      out.write("                <!-- Dropdown header -->\r\n");
      out.write("                <div class=\"px-3 py-3\">\r\n");
      out.write("                  <h6 class=\"text-sm text-muted m-0\">You have <strong class=\"text-primary\">13</strong> notifications.</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- List group -->\r\n");
      out.write("                <div class=\"list-group list-group-flush\">\r\n");
      out.write("                  <a href=\"#!\" class=\"list-group-item list-group-item-action\">\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                      <div class=\"col-auto\">\r\n");
      out.write("                        <!-- Avatar -->\r\n");
      out.write("                        <img alt=\"Image placeholder\" src=\"assets/img/theme/team-1.jpg\" class=\"avatar rounded-circle\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col ml--2\">\r\n");
      out.write("                        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                          <div>\r\n");
      out.write("                            <h4 class=\"mb-0 text-sm\">John Snow</h4>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"text-right text-muted\">\r\n");
      out.write("                            <small>2 hrs ago</small>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"text-sm mb-0\">Let's meet at Starbucks at 11:30. Wdyt?</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a href=\"#!\" class=\"list-group-item list-group-item-action\">\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                      <div class=\"col-auto\">\r\n");
      out.write("                        <!-- Avatar -->\r\n");
      out.write("                        <img alt=\"Image placeholder\" src=\"assets/img/theme/team-2.jpg\" class=\"avatar rounded-circle\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col ml--2\">\r\n");
      out.write("                        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                          <div>\r\n");
      out.write("                            <h4 class=\"mb-0 text-sm\">John Snow</h4>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"text-right text-muted\">\r\n");
      out.write("                            <small>3 hrs ago</small>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"text-sm mb-0\">A new issue has been reported for Argon.</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a href=\"#!\" class=\"list-group-item list-group-item-action\">\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                      <div class=\"col-auto\">\r\n");
      out.write("                        <!-- Avatar -->\r\n");
      out.write("                        <img alt=\"Image placeholder\" src=\"assets/img/theme/team-3.jpg\" class=\"avatar rounded-circle\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col ml--2\">\r\n");
      out.write("                        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                          <div>\r\n");
      out.write("                            <h4 class=\"mb-0 text-sm\">John Snow</h4>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"text-right text-muted\">\r\n");
      out.write("                            <small>5 hrs ago</small>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"text-sm mb-0\">Your posts have been liked a lot.</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a href=\"#!\" class=\"list-group-item list-group-item-action\">\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                      <div class=\"col-auto\">\r\n");
      out.write("                        <!-- Avatar -->\r\n");
      out.write("                        <img alt=\"Image placeholder\" src=\"../assets/img/theme/team-4.jpg\" class=\"avatar rounded-circle\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col ml--2\">\r\n");
      out.write("                        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                          <div>\r\n");
      out.write("                            <h4 class=\"mb-0 text-sm\">John Snow</h4>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"text-right text-muted\">\r\n");
      out.write("                            <small>2 hrs ago</small>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"text-sm mb-0\">Let's meet at Starbucks at 11:30. Wdyt?</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a href=\"#!\" class=\"list-group-item list-group-item-action\">\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                      <div class=\"col-auto\">\r\n");
      out.write("                        <!-- Avatar -->\r\n");
      out.write("                        <img alt=\"Image placeholder\" src=\"../assets/img/theme/team-5.jpg\" class=\"avatar rounded-circle\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col ml--2\">\r\n");
      out.write("                        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                          <div>\r\n");
      out.write("                            <h4 class=\"mb-0 text-sm\">John Snow</h4>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"text-right text-muted\">\r\n");
      out.write("                            <small>3 hrs ago</small>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"text-sm mb-0\">A new issue has been reported for Argon.</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- View all -->\r\n");
      out.write("                <a href=\"#!\" class=\"dropdown-item text-center text-primary font-weight-bold py-3\">View all</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item dropdown\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"#\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                <i class=\"ni ni-ungroup\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-dark bg-default  dropdown-menu-right \">\r\n");
      out.write("                <div class=\"row shortcuts px-4\">\r\n");
      out.write("                  <a href=\"#!\" class=\"col-4 shortcut-item\">\r\n");
      out.write("                    <span class=\"shortcut-media avatar rounded-circle bg-gradient-red\">\r\n");
      out.write("                      <i class=\"ni ni-calendar-grid-58\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <small>Calendar</small>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a href=\"#!\" class=\"col-4 shortcut-item\">\r\n");
      out.write("                    <span class=\"shortcut-media avatar rounded-circle bg-gradient-orange\">\r\n");
      out.write("                      <i class=\"ni ni-email-83\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <small>Email</small>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a href=\"#!\" class=\"col-4 shortcut-item\">\r\n");
      out.write("                    <span class=\"shortcut-media avatar rounded-circle bg-gradient-info\">\r\n");
      out.write("                      <i class=\"ni ni-credit-card\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <small>Payments</small>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a href=\"#!\" class=\"col-4 shortcut-item\">\r\n");
      out.write("                    <span class=\"shortcut-media avatar rounded-circle bg-gradient-green\">\r\n");
      out.write("                      <i class=\"ni ni-books\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <small>Reports</small>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a href=\"#!\" class=\"col-4 shortcut-item\">\r\n");
      out.write("                    <span class=\"shortcut-media avatar rounded-circle bg-gradient-purple\">\r\n");
      out.write("                      <i class=\"ni ni-pin-3\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <small>Maps</small>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a href=\"#!\" class=\"col-4 shortcut-item\">\r\n");
      out.write("                    <span class=\"shortcut-media avatar rounded-circle bg-gradient-yellow\">\r\n");
      out.write("                      <i class=\"ni ni-basket\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <small>Shop</small>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <ul class=\"navbar-nav align-items-center  ml-auto ml-md-0 \">\r\n");
      out.write("            <li class=\"nav-item dropdown\">\r\n");
      out.write("              <a class=\"nav-link pr-0\" href=\"#\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                <div class=\"media align-items-center\">\r\n");
      out.write("                  <span class=\"avatar avatar-sm rounded-circle\">\r\n");
      out.write("                    <img alt=\"Image placeholder\" src=\"assets/img/theme/team-4.jpg\">\r\n");
      out.write("                  </span>\r\n");
      out.write("                  <div class=\"media-body  ml-2  d-none d-lg-block\">\r\n");
      out.write("                    <span class=\"mb-0 text-sm  font-weight-bold\">John Snow</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"dropdown-menu  dropdown-menu-right \">\r\n");
      out.write("                <div class=\"dropdown-header noti-title\">\r\n");
      out.write("                  <h6 class=\"text-overflow m-0\">Welcome!</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"#!\" class=\"dropdown-item\">\r\n");
      out.write("                  <i class=\"ni ni-single-02\"></i>\r\n");
      out.write("                  <span>My profile</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#!\" class=\"dropdown-item\">\r\n");
      out.write("                  <i class=\"ni ni-settings-gear-65\"></i>\r\n");
      out.write("                  <span>Settings</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#!\" class=\"dropdown-item\">\r\n");
      out.write("                  <i class=\"ni ni-calendar-grid-58\"></i>\r\n");
      out.write("                  <span>Activity</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#!\" class=\"dropdown-item\">\r\n");
      out.write("                  <i class=\"ni ni-support-16\"></i>\r\n");
      out.write("                  <span>Support</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                <a href=\"#!\" class=\"dropdown-item\">\r\n");
      out.write("                  <i class=\"ni ni-user-run\"></i>\r\n");
      out.write("                  <span>Logout</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <div class=\"header bg-primary pb-6\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"header-body\">\r\n");
      out.write("          <div class=\"row align-items-center py-4\">\r\n");
      out.write("            <div class=\"col-lg-6 col-7\">\r\n");
      out.write("              <h6 class=\"h2 text-white d-inline-block mb-0\">Add New Booking</h6>\r\n");
      out.write("              <nav aria-label=\"breadcrumb\" class=\"d-none d-md-inline-block ml-md-4\">\r\n");
      out.write("                <ol class=\"breadcrumb breadcrumb-links breadcrumb-dark\">\r\n");
      out.write("                  <li class=\"breadcrumb-item\"><a href=\"#\"><i class=\"fas fa-home\"></i></a></li>\r\n");
      out.write("                  <li class=\"breadcrumb-item\"><a href=\"#\">Components</a></li>\r\n");
      out.write("                  <li class=\"breadcrumb-item active\" aria-current=\"page\">Add New Booking</li>\r\n");
      out.write("                </ol>\r\n");
      out.write("              </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6 col-5 text-right\">\r\n");
      out.write("              <a href=\"#\" class=\"btn btn-sm btn-neutral\">New</a>\r\n");
      out.write("              <a href=\"#\" class=\"btn btn-sm btn-neutral\">Filters</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Page content -->\r\n");
      out.write("    <div class=\"container-fluid mt--6\">\r\n");
      out.write("      <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\" col \">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-header bg-transparent\">\r\n");
      out.write("              <h3 class=\"mb-0\">Add New Booking</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <div class=\"row icon-examples\">\r\n");
      out.write("              \r\n");
      out.write("               <div class=\"col-xl-12 order-xl-1\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <form>\r\n");
      out.write("                <h6 class=\"heading-small text-muted mb-4\">User information</h6>\r\n");
      out.write("                <div class=\"pl-lg-4\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-control-label\" for=\"input-username\">Username</label>\r\n");
      out.write("                        <input type=\"text\" id=\"input-username\" class=\"form-control\" placeholder=\"Username\" value=\"lucky.jesse\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-control-label\" for=\"input-email\">Email address</label>\r\n");
      out.write("                        <input type=\"email\" id=\"input-email\" class=\"form-control\" placeholder=\"jesse@example.com\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-control-label\" for=\"input-first-name\">First name</label>\r\n");
      out.write("                        <input type=\"text\" id=\"input-first-name\" class=\"form-control\" placeholder=\"First name\" value=\"Lucky\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-control-label\" for=\"input-last-name\">Last name</label>\r\n");
      out.write("                        <input type=\"text\" id=\"input-last-name\" class=\"form-control\" placeholder=\"Last name\" value=\"Jesse\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <hr class=\"my-4\" />\r\n");
      out.write("                <!-- Address -->\r\n");
      out.write("                <h6 class=\"heading-small text-muted mb-4\">Contact information</h6>\r\n");
      out.write("                <div class=\"pl-lg-4\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-control-label\" for=\"input-address\">Address</label>\r\n");
      out.write("                        <input id=\"input-address\" class=\"form-control\" placeholder=\"Home Address\" value=\"Bld Mihail Kogalniceanu, nr. 8 Bl 1, Sc 1, Ap 09\" type=\"text\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-control-label\" for=\"input-city\">City</label>\r\n");
      out.write("                        <input type=\"text\" id=\"input-city\" class=\"form-control\" placeholder=\"City\" value=\"New York\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-control-label\" for=\"input-country\">Country</label>\r\n");
      out.write("                        <input type=\"text\" id=\"input-country\" class=\"form-control\" placeholder=\"Country\" value=\"United States\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-control-label\" for=\"input-country\">Postal code</label>\r\n");
      out.write("                        <input type=\"number\" id=\"input-postal-code\" class=\"form-control\" placeholder=\"Postal code\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <hr class=\"my-4\" />\r\n");
      out.write("                <!-- Description -->\r\n");
      out.write("                <h6 class=\"heading-small text-muted mb-4\">About me</h6>\r\n");
      out.write("                <div class=\"pl-lg-4\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"form-control-label\">About Me</label>\r\n");
      out.write("                    <textarea rows=\"4\" class=\"form-control\" placeholder=\"A few words about you ...\">A beautiful Dashboard for Bootstrap 4. It is Free and Open Source.</textarea>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("            \r\n");
      out.write("                            \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer class=\"py-5\" id=\"footer-main\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row align-items-center justify-content-xl-between\">\r\n");
      out.write("        <div class=\"col-xl-6\">\r\n");
      out.write("          <div class=\"copyright text-center text-xl-left text-muted\">\r\n");
      out.write("            &copy; Powered by <a href=\"https://www.creative-tim.com\" class=\"font-weight-bold ml-1\" target=\"_blank\">Fabzia Technologies LLP.</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xl-6\">\r\n");
      out.write("          <ul class=\"nav nav-footer justify-content-center justify-content-xl-end\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"https://www.fabzia.in\" class=\"nav-link\" target=\"_blank\">Fabzia</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"http://fabzia.in/about-us.php\" class=\"nav-link\" target=\"_blank\">About Us</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"http://blog.creative-tim.com\" class=\"nav-link\" target=\"_blank\">Blog</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <!-- <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md\" class=\"nav-link\" target=\"_blank\">MIT License</a>\r\n");
      out.write("            </li> -->\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  \r\n");
      out.write("   <!-- Core -->\r\n");
      out.write("  <script src=\"assets/vendor/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/js-cookie/js.cookie.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js\"></script>\r\n");
      out.write("  <!-- Optional JS -->\r\n");
      out.write("  <script src=\"assets/vendor/clipboard/dist/clipboard.min.js\"></script>\r\n");
      out.write("  <!-- Argon JS -->\r\n");
      out.write("  <script src=\"assets/js/argon.js?v=1.2.0\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
